server:
  port: 8882
spring:
  datasource:
    url: jdbc:mysql://localhost:2006/Relation?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false
